import { Platform } from "react-native";

const ELEVENLABS_API_KEY = process.env.EXPO_PUBLIC_ELEVENLABS_API_KEY;
const ELEVENLABS_STT_ENDPOINT = "https://api.elevenlabs.io/v1/speech-to-text";

export interface STTResponse {
  text: string;
  language_code?: string;
  language_probability?: number;
}

/**
 * Transcribes audio from a local URI using ElevenLabs Speech-to-Text API.
 *
 * @param audioUri Local URI of the recorded audio file
 * @param mimeType MIME type of the audio file (defaults to auto-detect or 'audio/m4a')
 * @returns Transcribed text string
 */
export async function transcribeAudio(
  audioUri: string,
  mimeType: string = "audio/m4a",
): Promise<string> {
  if (!ELEVENLABS_API_KEY) {
    throw new Error(
      "Missing EXPO_PUBLIC_ELEVENLABS_API_KEY environment variable.",
    );
  }

  if (!audioUri) {
    throw new Error("Audio file URI is required for transcription.");
  }

  try {
    const formData = new FormData();

    if (Platform.OS === "web") {
      // 1. Fetch the local blob/file generated by expo-av on web
      const response = await fetch(audioUri);
      const blob = await response.blob();

      // Detect actual WebM/OGG MIME type if expo-av recorded web audio
      const webMimeType = blob.type || mimeType || "audio/webm";
      const extension = webMimeType.includes("webm") ? "webm" : "m4a";
      const filename = `recording.${extension}`;

      const file = new File([blob], filename, { type: webMimeType });
      formData.append("file", file);
    } else {
      // 2. React Native Native (iOS / Android) format
      const filename = audioUri.split("/").pop() || "recording.m4a";

      formData.append("file", {
        uri: audioUri,
        name: filename,
        type: mimeType,
      } as unknown as Blob);
    }

    // ElevenLabs state-of-the-art ASR model
    formData.append("model_id", "scribe_v2");

    const apiResponse = await fetch(ELEVENLABS_STT_ENDPOINT, {
      method: "POST",
      headers: {
        "xi-api-key": ELEVENLABS_API_KEY,
      },
      body: formData,
    });

    if (!apiResponse.ok) {
      const errorData = await apiResponse.text();
      throw new Error(
        `ElevenLabs STT API error (${apiResponse.status}): ${errorData}`,
      );
    }

    const data: STTResponse = await apiResponse.json();

    if (!data.text) {
      throw new Error("ElevenLabs STT returned empty transcription text.");
    }

    return data.text.trim();
  } catch (error) {
    console.error("Error in transcribeAudio:", error);
    throw error;
  }
}
